# Generated by Django 5.0.9 on 2024-12-16 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionStageTime',
            fields=[
                ('TeacherID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='导师编号')),
                ('Name', models.CharField(max_length=50, verbose_name='名字')),
                ('Rest', models.IntegerField(verbose_name='缺额数量')),
                ('Abegin', models.DateTimeField(null=True, verbose_name='补选开始时间')),
                ('Aend', models.DateTimeField(null=True, verbose_name='补选结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('StudentID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='考生编号')),
                ('EnglishScore', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='英语成绩')),
                ('MathScore', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='数学成绩')),
                ('PoliticScore', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='政治成绩')),
                ('MajorScore', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='专业课成绩')),
            ],
            options={
                'verbose_name': '考生志愿信息',
                'verbose_name_plural': '考生志愿信息',
            },
        ),
        migrations.CreateModel(
            name='Choice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=100, unique=True, verbose_name='考生编号')),
                ('TeacherID', models.CharField(max_length=100, verbose_name='导师编号')),
            ],
            options={
                'verbose_name': '第一志愿',
                'verbose_name_plural': '第一志愿',
            },
        ),
        migrations.CreateModel(
            name='Choice2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=100, unique=True, verbose_name='考生编号')),
                ('TeacherID', models.CharField(max_length=100, verbose_name='导师编号')),
            ],
            options={
                'verbose_name': '第二志愿',
                'verbose_name_plural': '第二志愿',
            },
        ),
        migrations.CreateModel(
            name='Choice3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.CharField(max_length=100, unique=True, verbose_name='考生编号')),
                ('TeacherID', models.CharField(max_length=100, verbose_name='导师编号')),
            ],
            options={
                'verbose_name': '第三志愿',
                'verbose_name_plural': '第三志愿',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学院ID')),
                ('college_name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('total_recruit', models.IntegerField(default=0, verbose_name='总招生人数')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('StudentID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='考生编号')),
                ('WrittenExamScore', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='考生编号')),
                ('InterviewScore', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='面试成绩')),
                ('isadmitted', models.CharField(max_length=10, null=True, verbose_name='是否录取')),
            ],
            options={
                'verbose_name': '考生复试信息',
                'verbose_name_plural': '考生复试信息',
            },
        ),
        migrations.CreateModel(
            name='Mishulogin',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='身份编号')),
                ('password', models.CharField(default='student', max_length=12, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='MissedTeacher',
            fields=[
                ('TeacherID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='导师编号')),
                ('Name', models.CharField(max_length=50, verbose_name='名字')),
                ('begin', models.DateTimeField(null=True, verbose_name='补选开始时间')),
                ('end', models.DateTimeField(null=True, verbose_name='补选结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='OtherInfo',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='身份编号')),
                ('password', models.CharField(default='bjfuworker', max_length=12, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='StageTime',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('Fbegin', models.DateTimeField(verbose_name='第一阶段开始日期')),
                ('Fend', models.DateTimeField(verbose_name='第一阶段结束日期')),
                ('Sbegin', models.DateTimeField(verbose_name='第一阶段开始日期')),
                ('Send', models.DateTimeField(verbose_name='第一阶段结束日期')),
                ('Tbegin', models.DateTimeField(verbose_name='第一阶段开始日期')),
                ('Tend', models.DateTimeField(verbose_name='第一阶段结束日期')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=100, unique=True, verbose_name='学生编号')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('school', models.CharField(max_length=100, verbose_name='毕业学校')),
                ('phone', models.CharField(max_length=15, verbose_name='联系电话')),
                ('direction', models.CharField(max_length=100, verbose_name='学科方向')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
            },
        ),
        migrations.CreateModel(
            name='Studentlogin',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='身份编号')),
                ('password', models.CharField(default='student', max_length=12, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTotalScore',
            fields=[
                ('StudentID', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='考生编号')),
                ('program_name', models.CharField(max_length=255, null=True, verbose_name='学生方向')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('rank', models.IntegerField(null=True, verbose_name='排名')),
                ('is_admitted', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('TeacherID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='导师编号')),
                ('password', models.CharField(default='bjfuteacher', max_length=12, verbose_name='密码')),
                ('Name', models.CharField(max_length=50, verbose_name='邮箱')),
                ('Title', models.CharField(max_length=50, null=True, verbose_name='职称')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='teacher_photo/', verbose_name='导师个人照')),
                ('Biography', models.TextField(null=True, verbose_name='个人简介')),
                ('Email', models.EmailField(max_length=100, null=True, verbose_name='邮箱')),
                ('Phone', models.CharField(max_length=11, null=True, verbose_name='电话')),
                ('AcademicAchievements', models.TextField(max_length=100, null=True, verbose_name='学术成就')),
                ('EnrollmentQuota', models.IntegerField(default=0, null=True, verbose_name='招生指标')),
                ('Selected', models.IntegerField(default=0, verbose_name='选了多少学生')),
                ('QualificationReview', models.IntegerField(default=0, verbose_name='资格审查')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='XueKelogin',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='身份编号')),
                ('password', models.CharField(default='student', max_length=12, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='专业ID')),
                ('program_name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('total_recruit', models.IntegerField(verbose_name='总招生人数')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='web.college', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='ResearchDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_id', models.CharField(max_length=10, verbose_name='研究方向ID')),
                ('direction_name', models.CharField(max_length=100, verbose_name='研究方向名称')),
                ('exam_subjects', models.TextField(verbose_name='考试科目')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='web.program', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('studentId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='学生编号')),
                ('name', models.CharField(max_length=100, verbose_name='学生姓名')),
                ('gender', models.CharField(max_length=10, verbose_name='性别')),
                ('school', models.CharField(max_length=100, verbose_name='本科学校')),
                ('major', models.CharField(max_length=100, verbose_name='本科专业')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('direction', models.CharField(max_length=100, verbose_name='专业方向')),
                ('isadmitted', models.CharField(blank=True, max_length=10, null=True, verbose_name='是否录取')),
                ('FirstChoice', models.CharField(blank=True, max_length=10, null=True, verbose_name='第一志愿的导师编号')),
                ('SecondChoice', models.CharField(blank=True, max_length=10, null=True, verbose_name='第二志愿的导师编号')),
                ('ThirdChoice', models.CharField(blank=True, max_length=10, null=True, verbose_name='第三志愿的导师编号')),
                ('stage', models.IntegerField(blank=True, null=True, verbose_name='第几阶段被选')),
                ('FinalTeacher', models.ForeignKey(blank=True, db_column='FinalTeacher', null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.teacherinfo', verbose_name='最终的导师')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='web.researchdirection', verbose_name='研究方向')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='web.teacherinfo', verbose_name='导师')),
            ],
            options={
                'verbose_name': '研究方向导师关联',
                'verbose_name_plural': '研究方向导师关联',
            },
        ),
        migrations.AddConstraint(
            model_name='researchdirection',
            constraint=models.UniqueConstraint(fields=('program', 'direction_id'), name='unique_program_direction'),
        ),
    ]
