# Generated by Django 5.0.9 on 2024-12-16 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice1',
        ),
        migrations.DeleteModel(
            name='Choice2',
        ),
        migrations.DeleteModel(
            name='Choice3',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
