# Generated by Django 5.0.9 on 2024-12-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_choice1_delete_choice2_delete_choice3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='QualificationReview',
            field=models.IntegerField(default=0, null=True, verbose_name='资格审查'),
        ),
    ]
