# Generated by Django 5.0.9 on 2024-12-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_teacherinfo_qualificationreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNameView',
            fields=[
                ('TeacherID', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='导师编号')),
                ('Name', models.CharField(max_length=50, verbose_name='导师姓名')),
            ],
            options={
                'db_table': 'teachername',
                'managed': False,
            },
        ),
    ]
